spring:
  application:
    name: validation-service
  profiles:
    active: local

---
# Local development profile
logging:
  level:
    root: INFO
    com:
      flexi: DEBUG
    
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:9093
  cloud:
    function:
      definition: processing
    stream:
      kafka:
        binder:
          brokers: localhost:9093
          producer-properties:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer  
          consumer-properties:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        processing-in-0:
          destination: pipeline.validation
          group: ${spring.application.name}
        processing-out-0:
          destination: pipeline.outcoming
          producer:
            useNativeEncoding: false
        failed-out-0:
          destination: pipeline.failed
          producer:
            useNativeEncoding: false
    openfeign:
      client:
        config:
          model-registry:
            url: http://localhost:3001

server:
  port: 22010

management:
  endpoints:
    web:
      exposure:
        include: health,info,bindings