spring:
  application:
    name: validation-service
  profiles:
    active: local

---
# Local development profile
spring:
  config:
    activate:
      on-profile: local
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9093
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        processing-in-0:
          destination: pipeline.validation
          group: ${spring.application.name}
          content-type: application/json
        processing-out-0:
          destination: pipeline.outcoming
          content-type: application/json
        failed-out-0:
          destination: pipeline.failed
          content-type: application/json
    openfeign:
      client:
        config:
          model-registry:
            url: http://localhost:3001

logging:
  level:
    root: INFO
    com:
      flexi: DEBUG

server:
  port: 22010
management:
  endpoints:
    web:
      exposure:
        include: health,info,bindings,metrics,prometheus
---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        processing-in-0:
          destination: pipeline.validation
          group: ${spring.application.name}
          content-type: application/json
        processing-out-0:
          destination: pipeline.outcoming
          content-type: application/json
        failed-out-0:
          destination: pipeline.failed
          content-type: application/json
    openfeign:
      client:
        config:
          model-registry:
            url: http://model-registry:8080

logging:
  level:
    root: INFO
    com:
      flexi: INFO

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,bindings